### ISSUE TITLE
The notification doorhanger is no longer displayed if an enable "DNS Over HTTPS" enterprise policy is configured

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla/doh-rollout#123]
[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Affected Versions]:
- Firefox Unbranded Release 69.0, Build ID 20190827005903

[Prerequisites]:
- The doh-rollout@mozilla.org-0.0.9-rc1-signed.xpi add-on is installed.
- Have an enable "DNS Over HTTPS" policy active.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to "about:config".
2. Add the "doh-rollout.enabled" boolean pref with the "true" value.
3. Observe the behavior.

[Expected result]:
- The DoH notification doorhanger is displayed.

[Actual result]:
- The DoH notification doorhanger is not displayed.

[Notes]:
- The "enable_doh" telemetry event is sent and the "netowrk.trr.mode" pref is set to "2".
- The issue is reproducible using both policies.json files and policies set via the Local Group Policy Editor.
- I have attached a screen recording of the issue:
![policy_enabled_no_door](https://user-images.githubusercontent.com/40393891/65877584-b7cf6c80-e394-11e9-949e-bb8d68c56838.gif)

**Comment by maxxcrawford** [comment]
@Softvision-PatriciuPop This is expected – as the user has no option to opt out or in if an enterprise policy is set. 

@nhi-nguyen Can you confirm?

**Comment by nhi-nguyen** [comment]
The door hanger behaviour is as expected - we're not displaying it because it is not the addon that turns on DoH, but the enterprise policy.

I do see an issue here with the telemetry: it looks like the telemetry events has everything set (`"browserParent": "enable_doh", "google": "enable_doh", "policy": "enable_doh" ...`). With this telemetry event, we cannot tell why DoH is enabled.

Either this is a test setup issue, or a telemetry bug.

@Softvision-PatriciuPop, please test with only enterprise policy, and no other condition (safe search, canary domain etc.) and verify that in the telemetry event, only `"policy"` is set to `"enabled_doh"` and no other fields.

@maxxcrawford, to reduce turnaround time, could you verify that there's no bug in the telemetry implementation. I am suspecting a bug because as far as I can remember, we stop all other checks once we detect a policy in place.

**Comment by SoftVision-CarmenFat** [comment]
- We only used the setup for the enterprise policy, there was no "Safe Search" nor "Canary Domain" activated when tested this scenario. 
- This behavior was reproducible on the previous versions of the add-on as well. All the heuristics are displayed as "enable_doh", not just the "policy" one.

**Comment by maxxcrawford** [comment]
Note that with this version, the default policy return is now `no_policy_set`. If we receive a "enable_doh" response for policy, it means that they have a positive policy set. 

@nhi-nguyen The telemtery report has every field filled out because of how the heuristics function runs. When it does, it tests and checks each heuristics field (Google, Canary, etc). This is ran to determine the policy status on startup – however, we only have logic to disable DoH/doorhanger because of the policy. Any other "disable doh" heuristics response is determined later in the app callstack.

**Comment by maxxcrawford** [comment]
I think we can mark this issue as invalid/as expected.
